# Generated by Django 4.1.5 on 2023-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_name_alter_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='kaggle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='kaggle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='kaggle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
