# Generated by Django 4.1.5 on 2023-03-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_competition_totalcompetitors_and_more'),
        ('api', '0008_verifycode'),
    ]

    operations = [
    ]
